version: '3.8'

services:

  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db

  #Database Service
  db:
    image : mysql
    container_name : mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: books
      MYSQL_ROOT_PASSWORD: password
  

  # Application Service
  app:
    container_name: books
    build: 
      context: .
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
